version: "3"
services:
  server:
    build:
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app # Mount the server directory to /app
    ports:
      - "5000:5000"
    depends_on:
      - mongodb # Make sure the MongoDB service is started before the server
  web:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./client:/app # Mount the client directory to /app
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
